# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{xbmc-client}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christoph Olszowka"]
  s.date = %q{2010-11-25}
  s.description = %q{A simple API client for the XBMC Media Center JSON-RPC API}
  s.email = %q{christoph at olszowka de}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".rvmrc",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "examples/audio_library.rb",
     "examples/example_environment.rb",
     "lib/ruby_ext.rb",
     "lib/xbmc-client.rb",
     "lib/xbmc/command.rb",
     "test/helper.rb",
     "test/test_xbmc-client.rb",
     "xbmc-client.gemspec"
  ]
  s.homepage = %q{http://github.com/colszowka/xbmc-client}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A simple API client for the XBMC Media Center JSON-RPC API}
  s.test_files = [
    "test/helper.rb",
     "test/test_xbmc-client.rb",
     "examples/audio_library.rb",
     "examples/example_environment.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0.6.0"])
      s.add_runtime_dependency(%q<json>, [">= 1.4.5"])
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0.0"])
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, ["= 2.10.3"])
      s.add_development_dependency(%q<rdoc>, [">= 2.4.2"])
    else
      s.add_dependency(%q<httparty>, [">= 0.6.0"])
      s.add_dependency(%q<json>, [">= 1.4.5"])
      s.add_dependency(%q<activesupport>, [">= 3.0.0"])
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<shoulda>, ["= 2.10.3"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0.6.0"])
    s.add_dependency(%q<json>, [">= 1.4.5"])
    s.add_dependency(%q<activesupport>, [">= 3.0.0"])
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<shoulda>, ["= 2.10.3"])
  end
end

